config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    resources :carros
  end
  resources :tickets do
    resources :carros
  end
  resources :invoices do 
    resources :carros
  end
  resources :people 
  resources :registries
  resources :carros
  
  get 'registrostotales/',to: 'registries#mostrar', as: 'registro'
  get 'nuevo/',to: 'carros#nuevo', as: 'nuevo'
 
  devise_for :users
  get 'welcome/index'
  resources :users

  root 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :user
  has_many :registry
  

  	
    #Validacion nombre no null
	validates :nombre , presence: { message: "no debe estar vacio"} , confirmation: true
    #Validacion nombre solo letras
    validates :nombre, format: { with: /\A[a-zA-Z]+\z/,
    message: "Solo se aceptan letras" }
    #Validacion tamaño del nombre
    validates :nombre, length: { minimum: 2 }
    validates :nombre, length: { maximum: 50 }
    #Validacion rol no null
	validates :rol , presence: { message: "Valor neto no debe estar vacio"} , confirmation: true
    #Validacion rol solo numeros
    validates :rol, format: { with: /\A[0-9]+\z/, message: "Solo se aceptan numeros" }
    #validacion rol numero de 1 al 3
    validates :rol, format: { with: /\A[123]+\z/, message: "Solo se aceptan numero del 1 al 3" }
    validates :rol, length: { in: 1..1, message: "Solo deben ser unidades" }
	validates :telefono , presence: { message: "telefono no debe estar vacio"} , confirmation: true
    #Validacion telefono solo numeros
    validates :telefono, format: { with: /\A[0-9]+\z/, message: "Solo se aceptan numeros" }
    #Validacion telefono maximo 11 digitos
    validates :telefono, length: { maximum: 11 }



    
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])
  end

  # GET /people/new
  def new
    @person = Person.new
    @user_id = User.joins('INNER JOIN user on ')
  end

  # GET /people/1/edit
  def edit
    
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = current_user.create_person(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    def validate_user
      redirect_to new_user_session_path, notice: "necesitas iniciar sesión"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:user_id, :nombre, :rol, :telefono)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibido guardar esta persona:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
    <%= f.label :rol %><br>
    <%= options_for_select([['Jefe (ingrese un 1)',1], ['Vendedor (ingrese un 2)', 2], ['Seguridad (ingrese un 3)', 3]]) %>
  <div class="field">
    <%= f.number_field :rol %>
  </div>
  
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>  

  <div class="actions">
    <%= f.submit "Ingresar Persona" %>
  </div>


<% end %>

app/views/people/edit.html.erb
<h1>Editando Persona</h1>


<%= render 'form' %>

<%= link_to 'Ver', @person %> |
<%= link_to 'Volver', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Personas</h1>

<table>
  <thead>
    <tr>
      
      <th>Nombre</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        
        <td><%= person.nombre %></td>
        <td><%= link_to 'Editar', edit_person_path(person) %></td>
        <td><%= link_to 'ver', person %></td>
        <td><%= link_to 'Eliminar', person, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  
<%= link_to 'Nueva Persona', new_person_path %> |
<%= link_to 'registros', registries_path %>

app/views/people/new.html.erb
<h1>Nueva Persona</h1>

<%= render 'form' %>

<%= link_to 'Volver', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Mostrar Personas </h1>
<table class= "striped">
  <thead>
    <tr>
      <th data-field="nombre">Nombre</th>
      <th data-field="rol">Rol</th>
      <th data-field="telefono">Telefono</th>
      
      

    </tr>

  </thead>
  <tbody>
    <td><%= @person.nombre %></td>
    <% if @person.rol==1 %>
      <td>Jefe</td>
      <%end%>
      <% if @person.rol==2 %>
        <td>Vendedor</td>
        <%end%>
        <%if @person.rol==3%>
        <td>Seguridad</td>
    <%end%>
    <td><%= @person.telefono %></td>
  </tbody>
</table> 

<%= link_to 'Ver Registros', registro_path(:camp => @person.id) %> |
<%= link_to 'marcar hora', registry_path %> |
<%= link_to 'Volver', people_path %>