config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    resources :carros
  end
  resources :tickets do
    resources :carros
  end
  resources :invoices do 
    resources :carros
  end
  resources :people 
  resources :registries
  resources :carros
  
  get 'registrostotales/',to: 'registries#mostrar', as: 'registro'
  get 'nuevo/',to: 'carros#nuevo', as: 'nuevo'
 
  devise_for :users
  get 'welcome/index'
  resources :users

  root 'welcome#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_one :user
	has_one :carro

    #validacion tipo_documento no null
	validates :tipo_documento, presence: {message: "No debe estar vacio"}, confirmation: true
	#Validacion tipo_documento solo numeros
    validates :tipo_documento, format: { with: /\A[0-9]+\z/, message: "Solo se aceptan numeros" }
    #validacion tipo_pago entre 1 al 5
    
    #Validacion valor_neto no null
	validates :valor_neto , presence: { message: "Valor neto no debe estar vacio"} , confirmation: true
    #Validacion valor_neto solo numeros
    validates :valor_neto, format: { with: /\A[0-9.]+\z/, message: "Solo se aceptan numeros" }
    #Validacion valor_neto debe ser mayor que cero
    validates :valor_neto, :numericality => { :greater_than => 0, message: "debe ser mayor a cero"}
    #Validacion folio no null
	validates :folio , presence: { message: "Folio no debe estar vacio"} , confirmation: true
    #Validacion folio solo numeros
    validates :folio, format: { with: /\A[0-9]+\z/, message: "Solo se aceptan numeros" }
    #Validacion folio maximo 11 digitos
    validates :folio, length: { maximum: 11 }

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Factura fue creada con exito.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Factura fue actualizada con exito.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Factura fue eliminada con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:tipo_documento, :valor_neto, :folio)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_documento %><br>
    <%= options_for_select([['Ordinaria (ingrese un 1)',1], ['Simplificada (ingrese un 2)', 2], ['Rectificada (ingrese un 3)', 3],['Recapitulada (ingrese un 4)', 4],['Electronica (ingrese un 5)', 4]]) %>
    <%= f.number_field :tipo_documento %>
  </div>
  <div class="field">
    <%= f.label :valor_neto %><br>
    <%= f.number_field :valor_neto %>
  </div>
  <div class="field">
    <%= f.label :folio %><br>
    <%= f.number_field :folio %>
  </div>
  <div class="actions">
    <%= f.submit "Crear Factura" %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editar Facturas</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @invoice %> |
<%= link_to 'Volver', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Facturas</h1>

<table>
  <thead>
    <tr>
      
      <th>Folio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        
        <td><%= invoice.folio %></td>
        <td><%= link_to 'Mostrar', invoice %></td>
        <td><%= link_to 'Editar', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'agregar productos', nuevo_path %></td>
        <td><%= link_to 'Eliminar', invoice, method: :delete, data: { confirm: '¿Estas Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Factura', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>Nueva Factura</h1>

<%= render 'form' %>

<%= link_to 'Volver', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Mostrar Facturas </h1>
<table class= "striped">
  <thead>
    <tr>
      <th data-field="tipo_documento">Tipo de Documento</th>
      <th data-field="valor_neto">Valor neto</th>
      <th data-field="folio">Folio</th>
      


    </tr>

  </thead>
  <tbody>
    <td><%= @invoice.tipo_documento %></td>
    <td><%= @invoice.valor_neto %></td>
    <td><%= @invoice.folio %></td>
  </tbody>
</table>  
<%= link_to 'Editar', edit_invoice_path(@invoice) %> |
<%= link_to 'Volver', invoices_path %>