config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    resources :carros
  end
  resources :tickets do
    resources :carros
  end
  resources :invoices do 
    resources :carros
  end
  resources :people 
  resources :registries
  resources :carros
  
  get 'registrostotales/',to: 'registries#mostrar', as: 'registro'
  get 'nuevo/',to: 'carros#nuevo', as: 'nuevo'
 
  devise_for :users
  get 'welcome/index'
  resources :users

  root 'welcome#index'

end

app/models/registry.rb
class Registry < ActiveRecord::Base
  belongs_to :people
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /registries
  # GET /registries.json
  def index
    @registries = Registry.all
  end

  # GET /registries/1
  # GET /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries
  # POST /registries.json
  def create
    @registry = Registry.create(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to @registry }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  def mostrar
    persona = params[:camp]
    @registry = Registry.where(people_id: persona) 
  end

  # PATCH/PUT /registries/1
  # PATCH/PUT /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry}
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.json
  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registry_params
      params.require(:registry).permit(:ingreso, :salida)
    end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= form_for(@registry, :html => { :role =>"form"}) do |f| %>
  <% if @registry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
      <% @registry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :persona %>
    <%= f.text_field :people_id%>
  </div>

  <div class="field">
    <%= f.label :ingreso %><br>
    <%= f.datetime_select :ingreso %>
  </div>
  
  <div class="actions">
    <%= f.submit "registrar entrada"%>
  </div>
<% end %>

app/views/registries/_salida.html.erb
<%= form_for(@registry) do |f| %>
  <% if @registry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
      <% @registry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :salida %>
    <%= f.datetime_select :salida %>
  </div>
  <div class="actions">
    <%= f.submit "registrar salida"%>
  </div>
<% end %>

app/views/registries/edit.html.erb
<h1>Marcando Salida</h1>

<%= render 'salida' %>

<%= link_to 'Volver', registries_path %>

app/views/registries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Registros</h1>

<table>
  <thead>
    <tr>
      <th>Ingreso</th>
      <th>Salida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registries.each do |registry| %>
      <tr>
        <td><%= registry.ingreso %></td>
        <td><%= registry.salida %></td>
        <td><%= link_to 'Mostrar', registry %></td>
        <td><%= link_to 'marcar salida', edit_registry_path(registry) %></td>
        <td><%= link_to 'Eliminar', registry, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Registro', new_registry_path %> |
<%= link_to 'Volver a Personas', people_path %>

app/views/registries/mostrar.html.erb
<% @registry.each do |registro| %>
<%= registro.ingreso %><br>
<%end%>

app/views/registries/new.html.erb
<h1>Nuevo Registro</h1>

<%= render 'form' %>

<%= link_to 'Volver', registries_path %>

app/views/registries/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Mostrar Registros </h1>
<table class= "striped">
  <thead>
    <tr>
      
      <th data-field="Ingreso">Ingreso</th>
      <th data-field="Salida">Salida</th>
      <th data-field="Horas Trabajadas">Horas Trabajadas</th>
      
      
      

    </tr>

  </thead>
  
  <% t0=@registry.ingreso%>
  <% t1=@registry.salida%>
  
  <%if( @registry.salida !=nil)%>
  <% t2 = (t1-t0)/3600 %>
  <%end%>
  <tbody>
    
    <td><%= @registry.ingreso %></td>
    <td><%= @registry.salida %></td>
    <td><%= t2 %></td>
  </tbody>
</table> 

  



<%= link_to 'Volver', registries_path %>