config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    resources :carros
  end
  resources :tickets do
    resources :carros
  end
  resources :invoices do 
    resources :carros
  end
  resources :people 
  resources :registries
  resources :carros
  
  get 'registrostotales/',to: 'registries#mostrar', as: 'registro'
  get 'nuevo/',to: 'carros#nuevo', as: 'nuevo'
 
  devise_for :users
  get 'welcome/index'
  resources :users

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>las tres B</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">


</head>
<body>

  <header>
    <%if !user_signed_in? %>
    <li class= "col-md center">
      <%=link_to "Iniciar sesion", new_user_session_path%>
    </li>
    <%else%>
        <nav class="be-red write large-padding">
          <ul class="no-list row center-xs">
            <li class="col-md">
            <h4><%= link_to "Inicio", root_path %></h4>
            </li>
            <li class="col-md">
              <h4><%= link_to "Boletas", tickets_path %></h4>    
            </li>
            <li class="col-md">
              <h4><%= link_to "Facturas", invoices_path %></h4>
            </li>
            <li class="col-md">
              <h4><%= link_to "Productos", products_path %></h4>
            </li>
            <li class="col-md">
              <h4><%= link_to "Personas", people_path %></h4>
            </li>
            <li class="col-md">
              <h4><%= link_to "Registrar horas", registries_path %></h4>
            </li>
              <h4><% if user_signed_in? %></h4>
            <li>
              <h4><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></h4>
            </li>
          <%end%>
        <%end%>
      </ul>
    </nav>
  </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>